import {
    IonToolbar,
    IonGrid,
    IonCol,
    IonRow,
    IonTitle,
    IonHeader,
    IonContent,
    IonCard,
    IonCardTitle,
    IonCardSubtitle,
    IonPage,
    IonCardContent,
    IonCardHeader,
    IonList,
    IonListHeader,
    IonItem,
    IonAvatar,
    IonLabel,
} from '@ionic/vue'

export default {
    IonToolbar,
    IonGrid,
    IonCol,
    IonRow,
    IonTitle,
    IonHeader,
    IonContent,
    IonCard,
    IonCardTitle,
    IonCardSubtitle,
    IonPage,
    IonCardContent,
    IonCardHeader,
    IonList,
    IonListHeader,
    IonItem,
    IonAvatar,
    IonLabel,
}